version: "2"
services:
  it-employee-db:
    image: postgres:15.1
    environment:
      - POSTGRES_PASSWORD=jukilo90
    ports:
      - "20032:5432"
    volumes:
      - "../scripts/postgres/001-create-it-employee-db.sql:/docker-entrypoint-initdb.d/001-create-it-employee-db.sql"

  it-employee-module:
    image: it-employee-backend-module:1.0.0-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=8000,suspend=n,server=y
    ports:
      - "20180:8080"
      - "20110:9010"
    volumes:
      - "./config/application-local.yml:/app/resources/application-local.yml"
    depends_on:
      - it-employee-db
